# Generated by Django 4.2.11 on 2024-04-02 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=254)),
                ('points', models.IntegerField()),
                ('trip_id', models.CharField(max_length=10)),
                ('head_sign', models.CharField(max_length=26)),
                ('direction', models.IntegerField()),
                ('route_id', models.CharField(max_length=11)),
                ('route_name', models.CharField(max_length=6)),
                ('route_long', models.CharField(max_length=79)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=254)),
                ('stop_name', models.CharField(max_length=254)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
                ('location_type', models.BigIntegerField()),
                ('parent_station', models.CharField(max_length=254)),
                ('trip_count', models.IntegerField()),
                ('trip_ids', models.CharField(max_length=251)),
                ('route_ids', models.CharField(max_length=254)),
                ('route_names', models.CharField(max_length=109)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Stations',
                'db_table': 'station',
            },
        ),
    ]
