# Generated by Django 4.2.11 on 2024-04-02 22:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='direction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='route',
            name='head_sign',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_long',
            field=models.CharField(max_length=79, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='shape_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='trip_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='location_type',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='parent_station',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='route_ids',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='route_names',
            field=models.CharField(max_length=109, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stop_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stop_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stop_long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stop_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='trip_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='trip_ids',
            field=models.CharField(max_length=251, null=True),
        ),
    ]
